### PR TITLE
Add guidelines for writing migration scripts

### PR DESCRIPTION
**Pull request by flin-8**
# Description

It's not clear when we need to write migration scripts. This is a source of confusing bugs given the pitfalls involved.
This document hopes to make it easy to make a decision.

Feel free to edit/suggest.

### CODE REVIEW

**Review by MarkSiedle — APPROVED** [review]
Love it + 100% agree. Adding various "defaults" or "conditional fill-ins" in our mainline code (because something may or may not exist) is horrible for future-us to have to reason about. We've still got various hacks in our frontend to protect against bad data/missing defaults etc.  that were very difficult to work through in the step-editor revamp for example.

You mentioned this was pretty raw, but I think this sums up the problem/solution/direction really well. It's a great foundation that we can iterate on in terms of guidance.

This is not a blocker, but do we have any recent PRs (from QRF or otherwise) that have resolved one of these issues? I had a quick look through the closed-PRs list, but none of the titles jumped out at me. If you know of any, would it be worth including an example PR that addresses/solves one of these problems (showing our recommended approach for DB migrations like these)?

LGTM

**Comment by flin-8** [comment]
> Love it + 100% agree. Adding various "defaults" or "conditional fill-ins" in our mainline code (because something may or may not exist) is horrible for future-us to have to reason about. We've still got various hacks in our frontend to protect against bad data/missing defaults etc. that were very difficult to work through in the step-editor revamp for example.
> 
> You mentioned this was pretty raw, but I think this sums up the problem/solution/direction really well. It's a great foundation that we can iterate on in terms of guidance.
> 
> This is not a blocker, but do we have any recent PRs (from QRF or otherwise) that have resolved one of these issues? I had a quick look through the closed-PRs list, but none of the titles jumped out at me. If you know of any, would it be worth including an example PR that addresses/solves one of these problems (showing our recommended approach for DB migrations like these)?
> 
> LGTM

I've added an example of a fix to the document (https://trello.com/c/Z5SnrNid/3764-variable-substitution-broken-for-steps-based-on-a-template)

**Comment by flin-8** [comment]
@NickJosevski did you want to add anything here?

**Comment by NickJosevski** [comment]
Looks good thanks for pinging me, this is an area I care a lot about in server as often I had to fix it.

If you need more examples, look back at old migration scripts, will be faster to spot repairs and the associated PRs + Issues

Good stuff mentioning:
 * pre-release versions
 * Serialization behaviour
 * Mainline code to add default

The mainline defaults/repairs - I'd call this out as something that **must be avoided and cleaned up if spotted.**

 > Remove any mainline patching code - as it only delays the bug hitting us. The more time that passes the more chance for the data to drift even further (subsequent patches may miss it if it's not recognisable).

**Review by NickJosevski — APPROVED** [review]
😄

**Pull request merged**
